// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Git ignore these

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhCFMeKzpL-enS9KNYXPbDTibHI4G1mM',
    appId: '1:98931983397:android:28e9749164ff6068a4abcc',
    messagingSenderId: '98931983397',
    projectId: 'courier-testing-61c0b',
    storageBucket: 'courier-testing-61c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWnYV_4reQ_nSvr_q1P5WwBoJajVj8bFk',
    appId: '1:98931983397:ios:bddf76ba344327bda4abcc',
    messagingSenderId: '98931983397',
    projectId: 'courier-testing-61c0b',
    storageBucket: 'courier-testing-61c0b.appspot.com',
    iosClientId: '98931983397-oc2rntk0nad0gvhghr924f2hbgd3nd5h.apps.googleusercontent.com',
    iosBundleId: 'com.courier.courierFlutterExample',
  );
}
